# Generated by Django 4.2.30 on 2026-06-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_address_options_alter_cart_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Phone Number'),
        ),
    ]
