services:
  - type: web
    name: ljs-storefront
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py loaddata store/fixtures/demo_data.json && python manage.py collectstatic --noinput
    startCommand: gunicorn jewelryshop.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com,synovalabs.tech,www.synovalabs.tech"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://synovalabs.tech,https://www.synovalabs.tech"
      - key: PAYPAL_CLIENT_ID
        value: ""
      - key: PYTHON_VERSION
        value: "3.12.0"
